version: 0.2.0

phases:
  install:
    runtime-versions:
      java: corretto11
    commands:
      - echo "Installing dependencies..."
      - mvn install

  build:
    commands:
      - echo "Building the project..."
      - mvn package

  post_build:
    commands:
      - echo "Post-build step..."

artifacts:
  files:
    - target/myproject.jar